version: '3.8'

services:
  dev-log:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: dev-log
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: Mount logs directory if needed
      - ./logs:/app/logs
    healthcheck:
      test: ['CMD', 'node', '-e', "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service with hot reload
  dev-log-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: dev-log-dev
    restart: unless-stopped
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./tsconfig.json:/app/tsconfig.json
    command: yarn dev
    profiles:
      - dev
